### ISSUE TITLE
Access denied from S3

### ISSUE THREAD

**Issue by mustafashabib** [oborseth/LocalS3Repo2#2]
Not sure what's going on but I just tried setting up this plugin with access credentials that I know have full access to S3 and I'm seeing this when I try to upload:

Any ideas? I'm using MediaWiki version 1.24.2

---

0  
 **Notice**: curl_setopt(): CURLOPT_SSL_VERIFYHOST with value 1 is deprecated and will be removed as of libcurl 7.28.1. It is recommended to use value 2 instead in **/opt/bitnami/apps/mediawiki/htdocs/extensions/LocalS3Repo/S3.php** on line **1230**  

**Warning**: S3::getObjectInfo(mybucket, /opt/bitnami/php/tmp/phpZU9HQy): [403] Unexpected HTTP status in **/opt/bitnami/apps/mediawiki/htdocs/extensions/LocalS3Repo/S3.php** on line **451**  

**Notice**: curl_setopt(): CURLOPT_SSL_VERIFYHOST with value 1 is deprecated and will be removed as of libcurl 7.28.1. It is recommended to use value 2 instead in **/opt/bitnami/apps/mediawiki/htdocs/extensions/LocalS3Repo/S3.php** on line **1230**  

**Warning**: S3::getObjectInfo(mybucket, wiki/temp/5/5f/20150527151014!phpZU9HQy.jpg): [403] Unexpected HTTP status in **/opt/bitnami/apps/mediawiki/htdocs/extensions/LocalS3Repo/S3.php** on line **451**  

**Notice**: curl_setopt(): CURLOPT_SSL_VERIFYHOST with value 1 is deprecated and will be removed as of libcurl 7.28.1. It is recommended to use value 2 instead in **/opt/bitnami/apps/mediawiki/htdocs/extensions/LocalS3Repo/S3.php** on line **1230**  

**Warning**: S3::getObjectInfo(mybucket, /opt/bitnami/php/tmp/phpZU9HQy): [403] Unexpected HTTP status in **/opt/bitnami/apps/mediawiki/htdocs/extensions/LocalS3Repo/S3.php** on line **451**  

**Notice**: curl_setopt(): CURLOPT_SSL_VERIFYHOST with value 1 is deprecated and will be removed as of libcurl 7.28.1. It is recommended to use value 2 instead in **/opt/bitnami/apps/mediawiki/htdocs/extensions/LocalS3Repo/S3.php** on line **1230**  

**Warning**: S3::putObject(): [AccessDenied] Access Denied in **/opt/bitnami/apps/mediawiki/htdocs/extensions/LocalS3Repo/S3.php** on line **365**

**Comment by RJSzynal** [comment]
First, I'd use Cariaso's fork at https://github.com/cariaso/LocalS3Repo
Second, I had to edit S3.php and replace "s3.amazonaws.com" with the specific location endpoint (in my case, "s3-eu-west-1.amazonaws.com") in the constructor function at line 193. The LocalSettings.php entry '$wgS3BaseUrl ' should be altered likewise.
Third, Make sure you have the appropriate security policy set for your mediawiki user (the user whos access ID and secret ID you're using) similar to the following:

``` json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "USER_SID",
            "Effect": "Allow",
            "Action": [
                "s3:DeleteObject",
                "s3:GetObject",
                "s3:GetObjectAcl",
                "s3:ListBucket",
                "s3:PutObject",
                "s3:PutObjectAcl"
            ],
            "Resource": [
                "arn:aws:s3:::BUCKET_NAME/IMAGES_FOLDER/*"
            ]
        }
    ]
}
```

Replacing USER_SID, BUCKET_NAME, and IMAGES_FOLDER with your appropriate values.

There really isn't much documentation for this extension but it is very useful.
